SELECT A.AUTHOR_ID, A.AUTHOR_NAME, AA.CATEGORY, SUM(AA.PRICE * AA.SALES) TOTAL_SALES
FROM AUTHOR A JOIN
(
    SELECT BS.BOOK_ID, BS.SALES, B.CATEGORY, B.AUTHOR_ID, B.PRICE
    FROM BOOK_SALES BS LEFT JOIN BOOK B
    ON BS.BOOK_ID = B.BOOK_ID
    WHERE TO_CHAR(BS.SALES_DATE, 'YYYY-MM') LIKE '2022-01%'
) AA
ON A.AUTHOR_ID = AA.AUTHOR_ID
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, AA.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
;