SELECT 
  TO_CHAR(SALES_DATE, 'YYYY') YEAR,
  TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) MONTH,
  A.GENDER GENDER,
  COUNT(DISTINCT(B.USER_ID)) USERS
FROM USER_INFO A, ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID
GROUP BY TO_CHAR(SALES_DATE, 'YYYY')
    , TO_NUMBER(TO_CHAR(SALES_DATE, 'MM'))
    , A.GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER
;