SELECT 
     FP.PRODUCT_ID
    ,FP.PRODUCT_NAME
    ,SUM(FP.PRICE * FO.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT FP JOIN FOOD_ORDER FO
    ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE TO_CHAR(FO.PRODUCE_DATE, 'YYYYMM') = '202205'
GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
;