SELECT AA.HISTORY_ID, (AA.RENT_DATE * AA.DAILY_FEE) * (100 - NVL(DISCOUNT_RATE, 0)) / 100 FEE
FROM 
    (SELECT 
        HISTORY_ID,
        H.END_DATE - H.START_DATE + 1 RENT_DATE,
        CASE 
            WHEN H.END_DATE - H.START_DATE + 1 >= 90 THEN '90일 이상'
            WHEN H.END_DATE - H.START_DATE + 1 >= 30 THEN '30일 이상'
            WHEN H.END_DATE - H.START_DATE + 1 >=  7 THEN '7일 이상'
        END AS DURATION_TYPE,
        CAR_TYPE,
        DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID) AA LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON AA.DURATION_TYPE = D.DURATION_TYPE AND AA.CAR_TYPE = D.CAR_TYPE
WHERE AA.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC
;