SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) SUM
    FROM (
        SELECT * FROM FIRST_HALF
        UNION ALL
        SELECT * FROM JULY
        )
    GROUP BY FLAVOR
    ORDER BY SUM DESC
) WHERE ROWNUM <= 3
;
